name: netPermissionHandler
description: Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android.


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.connectivity
        pluginClass: ConnectivityPlugin


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  dbus: ^0.7.8
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4
  test: ^1.22.0


